---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
  namespace: was
spec:
  accessModes:
    - ReadWriteOnce  # local-path는 ReadWriteMany 미지원
  resources:
    requests:
      storage: 20Gi  # 스토리지 크기 증가 (10Gi → 20Gi)
  storageClassName: local-path
