# security/serviceaccounts.yaml
# 제한적 ServiceAccount 및 보안 정책 설정 (PSP 제거)

# Web 계층 ServiceAccount (가장 제한적)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-account
  namespace: web
  labels:
    app: portfolio
    tier: frontend
    security.level: restricted
automountServiceAccountToken: false  # API 서버 접근 차단

---
# WAS 계층 ServiceAccount (제한적)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: was-service-account
  namespace: was
  labels:
    app: portfolio
    tier: backend
    security.level: restricted
automountServiceAccountToken: false  # API 서버 접근 차단

---
# DB 계층 ServiceAccount (가장 제한적)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-service-account
  namespace: db
  labels:
    app: portfolio
    tier: database
    security.level: restricted
automountServiceAccountToken: false  # API 서버 접근 차단

---
# Network Policy - Web 계층 (인그레스만 허용)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-network-policy
  namespace: web
spec:
  podSelector:
    matchLabels:
      tier: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # 인그레스 컨트롤러에서의 트래픽만 허용
  - from: []
    ports:
    - protocol: TCP
      port: 80
  egress:
  # WAS 계층으로만 트래픽 허용
  - to:
    - namespaceSelector:
        matchLabels:
          name: was
    ports:
    - protocol: TCP
      port: 5000
  # DNS 해석 허용
  - to: []
    ports:
    - protocol: UDP
      port: 53

---
# Network Policy - WAS 계층 (Web과 DB만 통신)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: was-network-policy
  namespace: was
spec:
  podSelector:
    matchLabels:
      tier: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Web 계층에서의 트래픽만 허용
  - from:
    - namespaceSelector:
        matchLabels:
          name: web
    ports:
    - protocol: TCP
      port: 5000
  egress:
  # DB 계층으로만 트래픽 허용
  - to:
    - namespaceSelector:
        matchLabels:
          name: db
    ports:
    - protocol: TCP
      port: 3306
  # DNS 해석 허용
  - to: []
    ports:
    - protocol: UDP
      port: 53

---
# Network Policy - DB 계층 (WAS에서만 접근)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-network-policy
  namespace: db
spec:
  podSelector:
    matchLabels:
      tier: database
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # WAS 계층에서의 트래픽만 허용
  - from:
    - namespaceSelector:
        matchLabels:
          name: was
    ports:
    - protocol: TCP
      port: 3306
  egress:
  # DNS 해석만 허용 (외부 통신 차단)
  - to: []
    ports:
    - protocol: UDP
      port: 53